### ISSUE TITLE
AGP8 mandates build.gradle to add namespace

### ISSUE THREAD

**Issue by wyq0918dev** [TerminalStudio/flutter_pty#7]
Add the following code in `android{}` of build.gradle
```
// Conditional for compatibility with AGP <4.2.
if (project.android.hasProperty("namespace")) {
    namespace 'com.example.flutter_pty'
}
```

**Comment by shadow3aaa** [comment]
Since this repo seems no longer being maintained, you can use this fork instead to fix this issue
```
dependencies:
// ...
  flutter_pty:
    git: https://github.com/shadow3aaa/flutter_pty
```
